name: Create Release Zip on Commit

on:
  push:
    branches:
      - midnight-ae2
      - daybreak-ae2

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get branch name
        id: branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        
      - name: Create zip file
        run: |
          zip -r ${{ steps.branch.outputs.branch }}.zip . \
            -x "*.git*" \
            -x "*node_modules/*" \
            -x "*.github/*"
      
      - name: Update latest release
        uses: andelf/nightly-release@main
        with:
          tag_name: ${{ steps.branch.outputs.branch }}-latest
          name: Latest Release - Branch ${{ steps.branch.outputs.branch }}
          files: ${{ steps.branch.outputs.branch }}.zip
          body: |
            Latest release for branch `${{ steps.branch.outputs.branch }}`
            
            This release is automatically updated on every commit to branch ${{ steps.branch.outputs.branch }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}